### ISSUE TITLE
TCD-TIMIT results

### ISSUE THREAD

**Issue by WillQuCD** [georgesterpu/Sigmedia-AVSR#1]
What about the results on TCD-TIMIT dataset? 
Could you share the results using different architectures with us?

**Comment by georgesterpu** [comment]
Sure, our recent publications include several evaluations on the TCD-TIMIT dataset, where we also mention what architectures we used:

https://georgesterpu.github.io/publications.html

We have an audio-only and audio-visual evaluation on the speaker-dependent set at the character/word level in our ICMI 2018 article. 
The ICIP 2018 one has a visual-only evaluation at the viseme level, yet the experiments were performed last year with slightly older architectures. With the ResNet CNN, viseme accuracy should be around 71%.

Although unpublished, when decoding characters directly from the visual stream alone should give a ~45% character error rate, ~72% word error rate.

It is a good idea to create a benchmark page.

**Comment by WillQuCD** [comment]
Great! Thanks for your contribution.
