### ISSUE TITLE
[AMSGrad] get running error in audio only training

### ISSUE THREAD

**Issue by LeeYongHyeok** [georgesterpu/Sigmedia-AVSR#12]
Hi, @georgesterpu. 

I do audio only test in my dataset.

so i fix some expriment_tcd_audio.py code to my unit_file & TFRecord path.

And then, i run my code. but i get running error in TensorFlow.

below is my error.

`WARNING:tensorflow:From /home/yong/project/yong_Sigmedia-AVSR/avsr/io_utils.py:208: tf_record_iterator (from tensorflow.python.lib.io.tf_record) is deprecated and will be removed in a future version.
Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`
WARNING:tensorflow:From /home/yong/project/yong_Sigmedia-AVSR/avsr/io_utils.py:113: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py:1419: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/yong/project/yong_Sigmedia-AVSR/avsr/encoder.py:44: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.batch_normalization instead.
WARNING:tensorflow:From /home/yong/project/yong_Sigmedia-AVSR/avsr/cells.py:24: GRUCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.GRUCell, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /home/yong/project/yong_Sigmedia-AVSR/avsr/cells.py:92: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /home/yong/project/yong_Sigmedia-AVSR/avsr/encoder.py:81: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn.py:626: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn_cell_impl.py:1259: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/seq2seq/python/ops/helper.py:311: Bernoulli.__init__ (from tensorflow.python.ops.distributions.bernoulli) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/distributions/bernoulli.py:97: Distribution.__init__ (from tensorflow.python.ops.distributions.distribution) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/seq2seq/python/ops/helper.py:314: Categorical.__init__ (from tensorflow.python.ops.distributions.categorical) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/distributions/categorical.py:278: multinomial (from tensorflow.python.ops.random_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.random.categorical instead.
/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py:110: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 511, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1175, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 977, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype float32 for Tensor with dtype resource: 'Tensor("Decoder/audio/Encoder/multi_rnn_cell/cell_0/gru_cell/gates/kernel/AMSGrad:0", shape=(), dtype=resource)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "experiment_lrs3_audio.py", line 61, in <module>
    main(sys.argv)
  File "experiment_lrs3_audio.py", line 44, in main
    num_gpus=1,
  File "/home/yong/project/yong_Sigmedia-AVSR/avsr/avsr.py", line 193, in __init__
    self._create_models()
  File "/home/yong/project/yong_Sigmedia-AVSR/avsr/avsr.py", line 381, in _create_models
    batch_size=self._hparams.batch_size[0])
  File "/home/yong/project/yong_Sigmedia-AVSR/avsr/avsr.py", line 418, in _make_model
    hparams=self._hparams
  File "/home/yong/project/yong_Sigmedia-AVSR/avsr/seq2seq.py", line 21, in __init__
    self._make_decoder()
  File "/home/yong/project/yong_Sigmedia-AVSR/avsr/seq2seq.py", line 101, in _make_decoder
    hparams=self._hparams
  File "/home/yong/project/yong_Sigmedia-AVSR/avsr/decoder_unimodal.py", line 59, in __init__
    self._init_decoder()
  File "/home/yong/project/yong_Sigmedia-AVSR/avsr/decoder_unimodal.py", line 118, in _init_decoder
    self._init_optimiser()
  File "/home/yong/project/yong_Sigmedia-AVSR/avsr/decoder_unimodal.py", line 465, in _init_optimiser
    zip(gradients, variables), global_step=tf.train.get_global_step())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 612, in apply_gradients
    update_ops.append(processor.update_op(self, grad))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 171, in update_op
    update_op = optimizer._resource_apply_dense(g, self._v)
  File "/home/yong/project/yong_Sigmedia-AVSR/avsr/AMSGrad.py", line 96, in _resource_apply_dense
    m_t = state_ops.assign(m, beta1_t * m + m_scaled_g_values, use_locking=self._use_locking)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 812, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 1078, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 5860, in mul
    "Mul", x=x, y=y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 547, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Mul' Op has type resource that does not match type float32 of argument 'x'.
Exception ignored in: <bound method AVSR.__del__ of <avsr.avsr.AVSR object at 0x7fa48a9e3470>>
Traceback (most recent call last):
  File "/home/yong/project/yong_Sigmedia-AVSR/avsr/avsr.py", line 198, in __del__
    self._train_session.close()
AttributeError: 'AVSR' object has no attribute '_train_session'`

I guess some TF version or whatelse...

what can i do for fix it?

thanks.

**Comment by georgesterpu** [comment]
Hi @LeeYongHyeok 
Thanks for opening this issue, I will have a look in a few hours today.

The deprecation warnings are ok, at least on tf 1.13. I was waiting for a more stable tensorflow/addons/seq2seq before porting our code, will give it another try soon.

**Comment by georgesterpu** [comment]
I can reproduce this error.

The AMSGrad optimiser is not compatible anymore with the latest stable version of TensorFlow. It is a third party implementation, and an issue has already been created on the original repository, see https://github.com/taki0112/AMSGrad-Tensorflow/issues/1

Since TensorFlow now officially supports AMSGrad through the keras api:
https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam
there is no point in supporting the third party implementation. It will just take some time until we fully transition to tf.keras.

Please use the Adam optimiser in the meantime.

**Comment by LeeYongHyeok** [comment]
Oh i see. 
I hope this issue can be fixed.
thanks for your reply.
