### ISSUE TITLE
[feature] minimum data length for stack log mel feature

### ISSUE THREAD

**Issue by LeeYongHyeok** [georgesterpu/Sigmedia-AVSR#14]
Hi @georgesterpu 

I do curriculum learning for LRS3 dataset.

So i cut the pretrain wav files to 1~3 words, (about 500ms), and make the feature TFRecord.

I make stacked log mel feature, stacked_w8s3 However, an error occurred.

I did not leave an error log, but I think the length of the wav file is short.

Is there a minimum length of data needed to create a stacked log mel feature?

**Comment by georgesterpu** [comment]
We only tried sentences as short as the shortest sentence in LRS2, sorry for not having an exact value right now.

There are multiple error sources that I can think of (stft code in tensorflow, the feature stacking code in numpy etc.), and it would be a lot easier if you provided an error log and/or a call stack.

However, I'd expect the code to run well on 500 ms audio segments.

Are you also using the latest code on the master branch ?
@saamc found a bug a couple of weeks ago, where the length of the noise segment could be [one sample shorter](https://github.com/georgesterpu/Sigmedia-AVSR/blob/master/avsr/awgn.py#L66) than the length of the input signal if you are unlucky enough with the random number generator.

**Comment by LeeYongHyeok** [comment]
@georgesterpu, Thanks for your reply.

I will try newest code.
