### ISSUE TITLE
 visemes and phonemes mapping

### ISSUE THREAD

**Issue by javadpeyman** [georgesterpu/Sigmedia-AVSR#15]
@georgesterpu  there are 16 classes of visemes in English. why you just use 12 visemes?
where is the mapping?

**Comment by georgesterpu** [comment]
@javadpeyman 
As far as I know, visemes are a subjective concept, and there is no unique recommended phoneme-to-viseme translation mapping. In [this work](https://arxiv.org/pdf/1805.11688.pdf) we used the Jeffers and Barley mapping (Jeffers and Barley, Speechreading , 1971, Charles C Thomas Publisher, Illinois) based on the findings of [this study](https://pdfs.semanticscholar.org/64e8/63479c159eed888746feba0a0579d84d64a9.pdf) comparing several existing mappings.

You might want to have a look at the work of Dr. Helen Bear @drylbear for more recent research on this topic.
