### ISSUE TITLE
How can I solve this problem 

### ISSUE THREAD

**Issue by ThompsonDadada** [georgesterpu/Sigmedia-AVSR#19]
Hello @georgesterpu, I have a problem now. When I execute extract_face.py after compiling Openface on Ubuntu16, I will get an error "Failed to open the video file at location:/media/guo/sewell/dataset/LRS2/mvlrs_v1/main/6386959537493875163/00004", the file is there. Have you solved such a problem?

**Comment by georgesterpu** [comment]
Hi @ThompsonDadada 
Could you please provide a full log to see which part of the code raises the error ?
My best guess is that you are missing a file extension.

I will have a busy day tomorrow, and will take a closer look from the day after.
Please also try to run openface directly in the command line on a single video.

Unfortunately this external tool lacks a Python interface to make things easier.

**Comment by ThompsonDadada** [comment]
Hi @georgesterpu 
Thank you very much for your reply! You're right. It's really a file extension problem. I added .mp4 to each line in the text you provided, and now it works. Thanks again.

**Comment by georgesterpu** [comment]
Nice, I am glad it worked.

Was it something wrong with the script itself, or does it need better documentation ?

Feature pre-processing is something that I don't test very often once the .tfrecord files are written.

**Comment by ThompsonDadada** [comment]
There's no problem with scripts, but I think you really need to write a more detailed document.
Or you should comment on the difference between preprocessing lrs2 and tcdtimit in scripts.

**Comment by ThompsonDadada** [comment]
Sorry, I'm having trouble generating TFRecords. When executing write_records_TCD program, it will report an error. I will post it below:

Traceback (most recent call last):
  File "write_records_tcd.py", line 58, in <module>
    main()
  File "write_records_tcd.py", line 34, in main
    test_record_name='/data/cqx/gjw/dataset/LRS2/tfrecords/characters_test_sd.tfrecord',
  File "/data/cqx/gjw/git/avsr-tf1-master/avsr/dataset_writer.py", line 47, in write_labels_records
    labels = _symbols_to_ints(ground_truth, unit_dict)
  File "/data/cqx/gjw/git/avsr-tf1-master/avsr/dataset_writer.py", line 286, in _symbols_to_ints
    ints = [unit_dict[symbol] for symbol in symbols]
  File "/data/cqx/gjw/git/avsr-tf1-master/avsr/dataset_writer.py", line 286, in <listcomp>
    ints = [unit_dict[symbol] for symbol in symbols]
KeyError: '4'

**Comment by georgesterpu** [comment]
The default vocabulary in `./avsr/misc/character_list` only includes letters from the English alphabet and two punctuation marks. It seems that your text contains digits as well. You can either:

- update your vocabulary with all the unknown tokens (e.g. digits)
- parse and tokenise the text (e.g. convert numbers to words)
- propose something more clever

Thanks for your feedback on improving documentation. I am currently writing my thesis, but will try to find time for it in the coming weeks.
