### ISSUE TITLE
Can u provice me the dataset?

### ISSUE THREAD

**Issue by zzp-appleLover** [georgesterpu/Sigmedia-AVSR#2]
hello. How can I get the TCD-TIMIT dataset? I create an acount in the website "https://sigmedia.tcd.ie/TCDTIMIT/''  but can't pass . I am a postgraduate, I want to run your model and try to use my own datas to train the model. Can u provice me the dataset? Thank u very much.

**Comment by georgesterpu** [comment]
Hi @zzp-appleLover 

The TCD-TIMIT dataset website is not managed by me and I am not quite sure who is in charge of it.

If you registered using your academic email address, then you have done your part well.

There is a manual verification step on the admin side that sometimes makes the whole process take more time than a researcher actually requires. I will try to find out who validates the accounts and let them know of the pending requests.

**Comment by zzp-appleLover** [comment]
Ok , I got it. Thank you very much. I am very grateful for your help.

**Comment by zzp-appleLover** [comment]
And I have another problem that if I can't get the TIMIT dataset, how can I preprocess my own dataset to the format of your model input? can u provide me the detail steps?

**Comment by georgesterpu** [comment]
I have forwarded your request two days ago and I hope it will get solved timely.

We don't have one fixed model with input restrictions, and the API is quite flexible in allowing you to define the pre-processing steps on your own.

Personally I use the OpenFace toolkit to detect and align the face track in a video, and this is the Python script: [extract_faces.py](https://github.com/georgesterpu/Sigmedia-AVSR/blob/master/extract_faces.py)

The AVSR class is designed to take paths to binary datasets in [Tensorflow's TFRecord format](https://www.tensorflow.org/tutorials/load_data/tf-records). We designed a TFRecordWriter class that does this for you, please have a look at its three methods `write_labels_records`, `write_audio_records` and `write_bmp_records` (last one takes the .bmp output of OpenFace), and also [at this script](https://github.com/georgesterpu/Sigmedia-AVSR/blob/master/write_records_tcd.py) for an example.

If by "our model" you refer to the attention-based audio-visual speech alignment strategy [presented at the ICMI conference](https://arxiv.org/abs/1809.01728), the essence should be the principle (frame-level alignment while still encoding), not necessarily the precise architecture we used. We know there are many combinations that don't work and several that do, and we're still studying this aspect. I strongly encourage you to try your own "flavours" and datasets, so we could learn more about this task.

**Comment by georgesterpu** [comment]
I am closing this issue for the lack of activity, but please feel free to re-open if there is something else I could help with.
