### ISSUE TITLE
Inquiry about aus csv generation

### ISSUE THREAD

**Issue by zzgg1** [georgesterpu/Sigmedia-AVSR#20]
Hello, I found we need csv files to use append aus in your code, do you mind if share how to generate aus csv files?

**Comment by georgesterpu** [comment]
Hi @zzgg1 

I have used the pre-trained models from the [OpenFace toolkit](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Action-Units) to estimate the Action Units intensities

The csv files are generated by OpenFace when the `extract_faces.py` script is used.
According to the [documentation](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments) of OpenFace, the action units should be enabled by default, and can also be enforced with the `-aus` flag.

If you have a different way to preprocess your video data other than with OpenFace, you would have to replace [this function](https://github.com/georgesterpu/avsr-tf1/blob/bfa70c04a5942d9c7d10020e62572bcb09245d45/avsr/dataset_writer.py#L554) that parses the AU annotations.

Let me know if this works for you.

**Comment by zzgg1** [comment]
Thanks, I would give it a try
