### ISSUE TITLE
What do the folders speaker-dependence and speaker-independence stand for?

### ISSUE THREAD

**Issue by xjwla** [georgesterpu/Sigmedia-AVSR#21]
What do the folders speaker-dependence and speaker-independence stand for?Thanks

**Comment by georgesterpu** [comment]
The directories in `master/datasets/tcdtimit/splits` contain the partitioning of the TCD-TIMIT dataset proposed by

> Harte, N.; Gillen, E., "TCD-TIMIT: An Audio-Visual Corpus of Continuous Speech," Multimedia, IEEE Transactions on , vol.17, no.5, pp.603,615, May 2015 doi: 10.1109/TMM.2015.2407694

Each volunteer in that dataset speaks a number of 98 sentences.
In the speaker dependent partitioning, each volunteer appears in both the train set and the test set, contributing with 67 and 31 sentences respectively. In the speaker independent setup, a volunteer is assigned to either the train partition or to the test one.

Does this answer your question ?

**Comment by xjwla** [comment]
Got it, thank you very much
