### ISSUE TITLE
Ask about transfer learning

### ISSUE THREAD

**Issue by wentaoxandry** [georgesterpu/Sigmedia-AVSR#4]
Hallo @georgesterpu,

I want use transfer learning  extract video features, I want ask if in your code this part is already done(like "Lip Reading Sentences in the Wild")? Or I have to implement by myself?

Thank you very much

**Comment by georgesterpu** [comment]
Hallo @wentaoxandry 

I don't fully understand your question. Do you want to use your own visual DNN to initialise the visual front-end in Sigmedia-AVSR ? Or do you want to train a multimodal seq2seq DNN from scratch, then transfer the parameters of the visual front-end to your own task ?

In our codebase there is no pre-training of the visual front-end done.
