### ISSUE TITLE
The program always be killed

### ISSUE THREAD

**Issue by wentaoxandry** [georgesterpu/Sigmedia-AVSR#5]
Hallo @georgesterpu ,

I'm using your code implement the algorithm in the paper "Lip reading sentences in the wild", but the program always be killed. It seems the program use too much memory and at end run out of memory.

~/Sigmedia-AVSR-LRS2$ ./run_av.sh
/home/wentao/.local/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Could not restore from checkpoint, training from scratch!

batch: 0
./run_av.sh: line 3:  2546 Killed                  python3 experiment_tcd_av.py 100000 0.1

My configure is like this
os.environ['CUDA_VISIBLE_DEVICES'] = "0"
os.environ['TF_CPP_MIN_LOG_LEVEL'] = "2"  # ERROR

def main(argv):

    num_epochs = int(argv[1])
    learning_rate = float(argv[2])

    experiment = avsr.AVSR(
        unit='character',
        unit_file='./avsr/misc/character_list',
        video_processing='resnet_cnn',
        cnn_filters=(8, 16, 32, 64),
        cnn_dense_units=64,
        batch_normalisation=True,
        video_train_record='./tfrecords/rgb36lips_train_sd.tfrecord',
        video_test_record='./tfrecords/rgb36lips_test_sd.tfrecord',
        audio_processing='features',
        audio_train_record='./tfrecords/mfcc_train_sd_stack_clean.tfrecord',
        audio_test_record='./tfrecords/mfcc_test_sd_stack_clean.tfrecord',
        labels_train_record ='./tfrecords/characters_train_sd.tfrecord',
        labels_test_record ='./tfrecords/characters_test_sd.tfrecord',
        encoder_type='unidirectional',
        architecture='bimodal',
        clip_gradients=True,
        max_gradient_norm=1.0,
        recurrent_l2_regularisation=0.0001,
        cell_type='lstm',
        highway_encoder=False,
        sampling_probability_outputs=0.1,
        embedding_size=128,
        dropout_probability=(0.9, 0.9, 0.9),
        decoding_algorithm='beam_search',     
        decoder_units_per_layer=((512,512,512)), #3 layers decoder
        encoder_units_per_layer=((256, 256, 256), (256, 256, 256)),  #3 layers encoder    
        attention_type=(('bahdanau', )*1, ('bahdanau', )*1),
        beam_width=10,
        batch_size=(48, 64),
        optimiser='AMSGrad',
        learning_rate=learning_rate,
	lr_decay=0.1,
        num_gpus=1,
    )

    # uer = experiment.evaluate(
    #    checkpoint_path='./checkpoints/tcd_video_to_chars/checkpoint.ckp-400',
    # )
    # print(uer)
    # return

    experiment.train(
        num_epochs=num_epochs,
        logfile='./logs/tcd_av_to_chars',
        try_restore_latest_checkpoint=True
    )

Have I doing something wrong?  Thank you very much.

By the way the warning is beginning at ;
def _make_model(self, graph, mode, batch_size)
in this step:
            model = Seq2SeqModel(
                data_sequences=(video_features, audio_features),
                mode=mode,
                hparams=self._hparams
            )

**Comment by georgesterpu** [comment]
Hallo @wentaoxandry 

I remember seeing a similar error whenever my system ran out of RAM.
Could you monitor the RAM usage after launching the experiment ?

Also, try reducing the buffer size of the function that shuffles the batches in memory:
https://github.com/georgesterpu/Sigmedia-AVSR/blob/master/avsr/io_utils.py#L89

**Comment by wentaoxandry** [comment]
Hallo @georgesterpu ,

Thank you for your help, I have try change buffer_size from 5000 to 100, but it getting better but still be killed, before change it can only do the first 3 batch, now after first 6 batch, it still be killed. 

The memory will always increase after each batch,

**Comment by georgesterpu** [comment]
What batch size are you using ?
And what is the average length (in seconds) of a sentence in your dataset ?

**Comment by wentaoxandry** [comment]
the batch size is still (48, 64), but I have also tried (24,32), still be killed.
the average length is 7s.

**Comment by georgesterpu** [comment]
What video resolution did you use when writing the video tfrecord files ?

**Comment by wentaoxandry** [comment]
I used output_resolution = (36,36)

**Comment by georgesterpu** [comment]
I believe that, for large scale experiments, we may need to redesign and optimise the input pipeline, but this won't happen until April.

Can you please confirm that your script gets killed when the system runs out of memory ?

**Comment by wentaoxandry** [comment]
Actually I also use lrs2 database, but I combine pretrain and train set and use the whole set as the training set, for test is still test set.

I can‘t find the specific script , but only know it is in avsr.py, the train function, 

in this while loop.
                       try:
                       while True:
                       out = self._train_session.run([self._train_model.model.train_op,
                                                   self._train_model.model.batch_loss,
                                                   ], **self.sess_opts)

                        if self._hparams.profiling is True:
                        self.profiler.add_step(batches, self.run_meta)

                        from tensorflow.python.profiler import option_builder

                        self.profiler.profile_name_scope(options=(option_builder.ProfileOptionBuilder
                                                                  .trainable_variables_parameter()))

                        opts = option_builder.ProfileOptionBuilder.time_and_memory()
                        self.profiler.profile_operations(options=opts)

                        opts = (option_builder.ProfileOptionBuilder(
                            option_builder.ProfileOptionBuilder.time_and_memory())
                                .with_step(batches)
                                .with_timeline_output('/tmp/timelines/').build())

                        self.profiler.profile_graph(options=opts)

                    sum_loss += out[1]
                    print('batch: {}'.format(batches))
                    batches += 1

**Comment by georgesterpu** [comment]
I see, LRS2 can have some very long sentences. Sigmedia-AVSR doesn't work well with those, as it fills up your memory quite fast.

**Comment by wentaoxandry** [comment]
ok, I understand, I will try first segment the pretrain set and than use it. Thank you so much.
